# Use the official Nginx image as the base image
FROM nginx

# Copy the Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port that Nginx is listening on
EXPOSE 80
